#!/bin/bash

htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Lifter-Scl-12-1/Lifter-Scl-12-1.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Lifter-Scl-12-1.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Lifter-Scl-12-BR/Lifter-Scl-12-BR.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Lifter-Scl-12-BR.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Lifter-Scl-24-1/Lifter-Scl-24-1.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Lifter-Scl-24-1.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Lifter-Scl-24-BR/Lifter-Scl-24-BR.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Lifter-Scl-24-BR.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Lifter-Scl-48-1/Lifter-Scl-48-1.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Lifter-Scl-48-1.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Lifter-Scl-48-BR/Lifter-Scl-48-BR.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Lifter-Scl-48-BR.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/PI240515-Scl-12-1/PI240515-Scl-12-1.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/PI240515-Scl-12-1.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/PI240515-Scl-12-BR/PI240515-Scl-12-BR.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/PI240515-Scl-12-BR.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/PI240515-Scl-24-1/PI240515-Scl-24-1.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/PI240515-Scl-24-1.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/PI240515-Scl-24-BR/PI240515-Scl-24-BR.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/PI240515-Scl-24-BR.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/PI240515-Scl-48-1/PI240515-Scl-48-1.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/PI240515-Scl-48-1.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/PI240515-Scl-48-BR/PI240515-Scl-48-BR.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/PI240515-Scl-48-BR.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Scl0205-12hr-1/Scl0205-12hr-1.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Scl0205-12hr-1.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Scl0205-12hr-BR/Scl0205-12hr-BR.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Scl0205-12hr-BR.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Scl0205-24-1/Scl0205-24-1.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Scl0205-24-1.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Scl0205-24-BR/Scl0205-24-BR.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Scl0205-24-BR.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Scl0205-48-1/Scl0205-48-1.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Scl0205-48-1.htout
htseq-count -f bam -s no -r pos -i name -m intersection-nonempty /home/peascl/scl_de/STARout_scl/Scl0205-48-BR/Scl0205-48-BR.Aligned.sortedByCoord.out.bam /home/peascl/scl_de/htout_STAR_scl/Sclsc1_GeneCatalog_genes_20110903.gff > /home/peascl/scl_de/htout_STAR_scl/Broad_gff/Scl0205-48-BR.htout